# Here we have already done 3 steps of EDA which is:

# 1. Data Cleaning

# 2. Missing Values and Imputation Technques

# 3. Data Analysis and Visualization

#It is already done in the previous notebook 

# Exploratory Data Analysis
!pip install pandas_profiling
!pip install sweetviz
#load the libraries
import pandas as pd
import numpy as np
import pandas_profiling as pp
import sweetviz as sv
data1 = pd.read_csv("C:/Users/saniyakhan/Downloads/data_clean.csv")
data1
data1.tail(10)
data1
#Data Structure 
type(data1)
data1.shape
#data types
data1.dtypes
#Data type conversion
data1.info()
data1
data2=data1.iloc[:,1:]
data2
#The method .copy() is used here so that any changes made in new DataFrame don't get reflected in the original one
data=data2.copy()
data['Month']=pd.to_numeric(data['Month'],errors='coerce')
data['Temp C']=pd.to_numeric(data['Temp C'],errors='coerce')# coerce will introduce NA values for non numeric data in the columns
data['Weather']=data['Weather'].astype('category')           #data['Wind']=data['Wind'].astype('int64')
data.info()
#Duplicates
#Count of duplicated rows
data[data.duplicated()].shape
data
#Print the duplicated rows
data[data.duplicated()]
data_cleaned1=data.drop_duplicates()
data_cleaned1.shape
#Drop columns
data_cleaned2=data_cleaned1.drop('Temp C',axis=1)
data_cleaned2
#Rename the columns
#rename the Solar column
data_cleaned3 = data_cleaned2.rename({'Solar.R': 'Solar'}, axis=1)
data_cleaned3
#Outlier Detection
# histogram of Ozone
data_cleaned3['Ozone'].hist()
#Box plot
data_cleaned3.boxplot(column=['Ozone'])
#Descriptive stat
data_cleaned3['Ozone'].describe()
data_cleaned3
#Bar plot
data['Weather'].value_counts().plot.bar()
#Missing Values and Imputation
import seaborn as sns
cols = data_cleaned3.columns 
colours = ['#000099', '#ffff00'] # specify the colours - yellow is missing. blue is not missing.
sns.heatmap(data_cleaned3[cols].isnull(),
            cmap=sns.color_palette(colours))
data_cleaned3[data_cleaned3.isnull().any(axis=1)].head()
data_cleaned3.isnull().sum()
#Mean Imputation
mean = data_cleaned3['Ozone'].mean()
print(mean)
data_cleaned3['Ozone'] = data_cleaned3['Ozone'].fillna(mean)
data_cleaned3
#Missing value imputation for categorical vlaue
#Get the object columns
obj_columns=data_cleaned3[['Weather']]
obj_columns.isnull().sum()
#Missing value imputation for categorical vlaue
obj_columns=obj_columns.fillna(obj_columns.mode().iloc[0])
obj_columns.isnull().sum()
data_cleaned3.shape
obj_columns.shape
#Join the data set with imputed object dataset
data_cleaned4=pd.concat([data_cleaned3,obj_columns],axis=1)
data_cleaned4.isnull().sum()
#Scatter plot and Correlation analysis
# Seaborn visualization library
import seaborn as sns
# Create the default pairplot
sns.pairplot(data_cleaned3)
#Correlation
data_cleaned3.corr()

# Transformations

In [ ]:
# Creating Dummy Variables for columns

In [9]:
data_cleaned4 = pd.get_dummies(data,columns=['Weather'])

In [10]:
data_cleaned4

Ozone  Solar.R  Wind  Temp C  Month  Day  Year  Temp  Weather_C  \
0     41.0    190.0   7.4    67.0    5.0    1  2010    67          0   
1     36.0    118.0   8.0    72.0    5.0    2  2010    72          1   
2     12.0    149.0  12.6    74.0    5.0    3  2010    74          0   
3     18.0    313.0  11.5    62.0    5.0    4  2010    62          0   
4      NaN      NaN  14.3    56.0    5.0    5  2010    56          0   
..     ...      ...   ...     ...    ...  ...   ...   ...        ...   
153   41.0    190.0   7.4    67.0    5.0    1  2010    67          1   
154   30.0    193.0   6.9    70.0    9.0   26  2010    70          0   
155    NaN    145.0  13.2    77.0    9.0   27  2010    77          0   
156   14.0    191.0  14.3    75.0    9.0   28  2010    75          0   
157   18.0    131.0   8.0    76.0    9.0   29  2010    76          1   

     Weather_PS  Weather_S  
0             0          1  
1             0          0  
2             1          0  
3             0          1  
4             0          1  
..          ...        ...  
153           0          0  
154           1          0  
155           0          1  
156           0          1  
157           0          0  

[158 rows x 11 columns]

In [11]:
data_cleaned4 = data_cleaned4.dropna()

In [12]:
data_cleaned4

Ozone  Solar.R  Wind  Temp C  Month  Day  Year  Temp  Weather_C  \
0     41.0    190.0   7.4    67.0    5.0    1  2010    67          0   
1     36.0    118.0   8.0    72.0    5.0    2  2010    72          1   
2     12.0    149.0  12.6    74.0    5.0    3  2010    74          0   
3     18.0    313.0  11.5    62.0    5.0    4  2010    62          0   
6     23.0    299.0   8.6    65.0    5.0    7  2010    65          0   
..     ...      ...   ...     ...    ...  ...   ...   ...        ...   
152   20.0    223.0  11.5    68.0    9.0   30  2010    68          0   
153   41.0    190.0   7.4    67.0    5.0    1  2010    67          1   
154   30.0    193.0   6.9    70.0    9.0   26  2010    70          0   
156   14.0    191.0  14.3    75.0    9.0   28  2010    75          0   
157   18.0    131.0   8.0    76.0    9.0   29  2010    76          1   

     Weather_PS  Weather_S  
0             0          1  
1             0          0  
2             1          0  
3             0          1  
6             1          0  
..          ...        ...  
152           0          1  
153           0          0  
154           1          0  
156           0          1  
157           0          0  

[114 rows x 11 columns]

In [ ]:
# Normalization of the data 

In [ ]:
# Import Libraries 

In [13]:
from numpy import set_printoptions
from sklearn.preprocessing import MinMaxScaler

In [14]:
data_cleaned4.values

array([[ 41. , 190. ,   7.4, ...,   0. ,   0. ,   1. ],
       [ 36. , 118. ,   8. , ...,   1. ,   0. ,   0. ],
       [ 12. , 149. ,  12.6, ...,   0. ,   1. ,   0. ],
       ...,
       [ 30. , 193. ,   6.9, ...,   0. ,   1. ,   0. ],
       [ 14. , 191. ,  14.3, ...,   0. ,   0. ,   1. ],
       [ 18. , 131. ,   8. , ...,   1. ,   0. ,   0. ]])

In [15]:
array = data_cleaned3.values
scaler = MinMaxScaler(feature_range=(0,1))
rescaledX = scaler.fit_transform(array[:,0:5])

In [ ]:
# Transformed data

In [16]:
set_printoptions(precision=2)
print(rescaledX[0:5,:])

[[0.24 0.56 0.3  0.   0.  ]
 [0.21 0.34 0.33 0.   0.03]
 [0.07 0.43 0.57 0.   0.07]
 [0.1  0.94 0.52 0.   0.1 ]
 [0.24  nan 0.66 0.   0.13]]


In [ ]:
# Standardize data (0 mean, 1 stdev)

In [ ]:
# Import library

In [17]:
from sklearn.preprocessing import StandardScaler

In [18]:
array = data_cleaned4.values
scaler = StandardScaler().fit(array)
rescaledX = scaler.transform(array)

In [ ]:
# Summarize transformed data

In [19]:
set_printoptions(precision=2)
print(rescaledX[0:5,:])

[[-0.02  0.05 -0.71 -1.15 -1.53 -1.7   0.   -1.15 -0.64 -0.68  1.28]
 [-0.17 -0.75 -0.54 -0.62 -1.53 -1.59  0.   -0.62  1.57 -0.68 -0.78]
 [-0.9  -0.41  0.77 -0.4  -1.53 -1.48  0.   -0.4  -0.64  1.47 -0.78]
 [-0.72  1.43  0.45 -1.69 -1.53 -1.36  0.   -1.69 -0.64 -0.68  1.28]
 [-0.57  1.27 -0.37 -1.37 -1.53 -1.02  0.   -1.37 -0.64  1.47 -0.78]]
